name: Starlight CD pipeline

on:
  push:
    branches:
      - "dev"
      - "*build*"
jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        compiler: [gcc-13]
    steps:
      - uses: actions/checkout@v2
      - name: Set scripts permissions
        run: chmod +x ./bin/*
      - name: Install system dependencies
        run: ./bin/deps.sh
      - name: Run static code check
        run: ./bin/run-static-analysis.sh
      - name: Run build
        run: ./bin/build.sh dev
      - name: Run unit tests
        run: pushd build && make test
      - name: Generate venv
        run: ./bin/venv.sh
      - name: Generate code coverage
        run: ./bin/generate-ut-cov.sh
      - name: Upload code coverage
        run: |
          curl -Os https://cli.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov --verbose upload-process --fail-on-error -t ${{ secrets.CODECOV_TOKEN }} \
            -n 'service'-${{ github.run_id }} -F service -f ./coverage/coverage.xml
