name: Starlight CD pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        compiler: [gcc-13]
    steps:
      - uses: actions/checkout@v2
      - name: Pull submodules
        run: git submodule update --init --recursive
      - name: Set scripts permissions
        run: chmod +x ./bin/*
      - name: Install system dependencies
        run: ./bin/deps.sh
      - name: Run build
        run: ./bin/build.sh
