name: Starlight unit tests runner

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: ./bin/install_deps.sh
    - name: Pull submodules
      run: git submodule update --init --recursive
    - name: Build 
      run: ./bin/build.sh
    - name: Run tests
      run: ./bin/run_tests.sh
