name: Starlight unit tests runner

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [gcc-10]
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          ./bin/install_deps.sh
          which g++
          which gcc
          which gcc-10
          which g++-10
      - name: Pull submodules
        run: git submodule update --init --recursive
      - name: Build
        run: ./bin/build.sh
    # - name: Run tests
    #   run: ./bin/run_tests.sh
